[package]
name = "num-order"
version = "0.0.1"
edition = "2018"

description = "Numerically consistent `Eq`, `Ord` and `Hash` implementations for various `num` types"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = { version = "0.2.0", optional = true }

[features]
default = ['libm']
std = []
